# To create and run the docker container in Power Shell or BASH:
#
# $ docker build --file Dockerfile_maya2022 -t mmsolver-linux-maya2022-build .
# $ docker run --rm --interactive --volume "${pwd}:/mmSolver" --tty mmsolver-linux-maya2022-build
#
#
# Once the docker image is built and run, you can execute the
# following...
#
#
# Install Python and run tools:
#
# $ source ./scripts/python_venv_activate_maya2022.bash
# $ ./scripts/python_linter_run_pylint.bash
# $ ./scripts/python_linter_run_flake8.bash
# $ ./scripts/python_linter_run_cpplint.bash
#
#
# Build CMake project:
#
# $ ./scripts/build_thirdparty_linux_maya2022.bash
# $ ./scripts/build_mmSolver_linux_maya2022.bash
#

FROM centos:7

RUN yum install --assumeyes \
       centos-release-scl \
       epel-release \
       deltarpm \
       yum-utils

# OpenSource "mesa" OpenGL Driver.
RUN yum install --assumeyes \
       mesa-libGLw \
       mesa-libGLU \
       mesa-utils \
       mesa-libGL-devel \
       mesa-libEGL-devel \
       mesa-libGLES-devel \
       mesa-libGLU-devel \
       mesa-libGLw-devel \
       libglvnd*64

# X11 utilities
RUN yum install --assumeyes \
       libXp \
       libXpm \
       libXmu \
       libXt \
       libXi \
       libXext \
       libX11 \
       libXinerama \
       libXau \
       libxcb \
       libXcomposite \
       xorg-x11-server-Xorg \
       xorg-x11-server-Xvfb \

# Install image libraries and setup fix for Maya to find libtiff.
RUN yum install --assumeyes \
       libpng12 \
       libtiff \
    && ln -s /usr/lib64/libtiff.so.5 /usr/lib64/libtiff.so.3

# Development tools for Maya 2022 and 2022.
RUN yum install --assumeyes \
       rh-python36 \
       rh-git218 \
       llvm-toolset-7-clang-tools-extra \
       cmake3 \
       devtoolset-9-gcc \
       devtoolset-9-gcc-c++ \
       devtoolset-9-make

# Install (latest) Rust.
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
    && source ${HOME}/.cargo/env

# Install Maya from archive.
ADD ./external/archives/Autodesk_Maya_2022_ML_Linux_64bit.tgz /temp
RUN rpm -Uvh /temp/Packages/Maya*.rpm && rm -r /temp
ENV MAYA_LOCATION=/usr/autodesk/maya/
ENV PATH=$MAYA_LOCATION/bin:$PATH

# Workaround for Maya "Segmentation fault (core dumped)" issue.
# See https://forums.autodesk.com/t5/maya-general/render-crash-on-linux/m-p/5608552/highlight/true
ENV MAYA_DISABLE_CIP=1

WORKDIR /mmSolver

ENTRYPOINT [ \
    "scl", "enable", \
               "rh-python36", \
               "devtoolset-9", \
               "llvm-toolset-7", \
               "rh-git218", \
                   "bash"]
