# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/share/Users/catte/dev/mayaMatchMoveSolver/python/mmSolver/tools/solver/ui/solver_layout.ui'
#
# Created: Sat Oct  6 01:06:35 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(803, 755)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.collection_layout = QtWidgets.QHBoxLayout()
        self.collection_layout.setSpacing(1)
        self.collection_layout.setObjectName("collection_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.collection_layout.addItem(spacerItem)
        self.collection_label = QtWidgets.QLabel(Form)
        self.collection_label.setObjectName("collection_label")
        self.collection_layout.addWidget(self.collection_label)
        self.collectionName_comboBox = QtWidgets.QComboBox(Form)
        self.collectionName_comboBox.setObjectName("collectionName_comboBox")
        self.collection_layout.addWidget(self.collectionName_comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.collection_layout.addItem(spacerItem1)
        self.collectionAdd_toolButton = QtWidgets.QToolButton(Form)
        self.collectionAdd_toolButton.setObjectName("collectionAdd_toolButton")
        self.collection_layout.addWidget(self.collectionAdd_toolButton)
        self.collectionRemove_toolButton = QtWidgets.QToolButton(Form)
        self.collectionRemove_toolButton.setObjectName("collectionRemove_toolButton")
        self.collection_layout.addWidget(self.collectionRemove_toolButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.collection_layout.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.collection_layout)
        self.objectAttribute_layout = QtWidgets.QHBoxLayout()
        self.objectAttribute_layout.setObjectName("objectAttribute_layout")
        self.object_layout = QtWidgets.QVBoxLayout()
        self.object_layout.setSpacing(1)
        self.object_layout.setObjectName("object_layout")
        self.object_frame = QtWidgets.QFrame(Form)
        self.object_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.object_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.object_frame.setObjectName("object_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.object_frame)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.objectAddRemove_layout = QtWidgets.QHBoxLayout()
        self.objectAddRemove_layout.setSpacing(1)
        self.objectAddRemove_layout.setObjectName("objectAddRemove_layout")
        self.object_label = QtWidgets.QLabel(self.object_frame)
        self.object_label.setObjectName("object_label")
        self.objectAddRemove_layout.addWidget(self.object_label)
        self.objectAdd_toolButton = QtWidgets.QToolButton(self.object_frame)
        self.objectAdd_toolButton.setObjectName("objectAdd_toolButton")
        self.objectAddRemove_layout.addWidget(self.objectAdd_toolButton)
        self.objectRemove_toolButton = QtWidgets.QToolButton(self.object_frame)
        self.objectRemove_toolButton.setObjectName("objectRemove_toolButton")
        self.objectAddRemove_layout.addWidget(self.objectRemove_toolButton)
        self.verticalLayout_5.addLayout(self.objectAddRemove_layout)
        self.object_treeView = QtWidgets.QTreeView(self.object_frame)
        self.object_treeView.setObjectName("object_treeView")
        self.verticalLayout_5.addWidget(self.object_treeView)
        self.object_layout.addWidget(self.object_frame)
        self.objectAttribute_layout.addLayout(self.object_layout)
        self.attribute_layout = QtWidgets.QVBoxLayout()
        self.attribute_layout.setSpacing(1)
        self.attribute_layout.setObjectName("attribute_layout")
        self.attribute_frame = QtWidgets.QFrame(Form)
        self.attribute_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.attribute_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.attribute_frame.setObjectName("attribute_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.attribute_frame)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.attributeAddRemove_layout = QtWidgets.QHBoxLayout()
        self.attributeAddRemove_layout.setSpacing(1)
        self.attributeAddRemove_layout.setObjectName("attributeAddRemove_layout")
        self.attribute_label = QtWidgets.QLabel(self.attribute_frame)
        self.attribute_label.setObjectName("attribute_label")
        self.attributeAddRemove_layout.addWidget(self.attribute_label)
        self.attributeAdd_toolButton = QtWidgets.QToolButton(self.attribute_frame)
        self.attributeAdd_toolButton.setObjectName("attributeAdd_toolButton")
        self.attributeAddRemove_layout.addWidget(self.attributeAdd_toolButton)
        self.attributeRemove_toolButton = QtWidgets.QToolButton(self.attribute_frame)
        self.attributeRemove_toolButton.setObjectName("attributeRemove_toolButton")
        self.attributeAddRemove_layout.addWidget(self.attributeRemove_toolButton)
        self.verticalLayout_6.addLayout(self.attributeAddRemove_layout)
        self.attribute_treeView = QtWidgets.QTreeView(self.attribute_frame)
        self.attribute_treeView.setObjectName("attribute_treeView")
        self.verticalLayout_6.addWidget(self.attribute_treeView)
        self.attribute_layout.addWidget(self.attribute_frame)
        self.objectAttribute_layout.addLayout(self.attribute_layout)
        self.verticalLayout_4.addLayout(self.objectAttribute_layout)
        self.solver_layout = QtWidgets.QVBoxLayout()
        self.solver_layout.setSpacing(1)
        self.solver_layout.setObjectName("solver_layout")
        self.solver_frame = QtWidgets.QFrame(Form)
        self.solver_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.solver_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.solver_frame.setObjectName("solver_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.solver_frame)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.solver_label = QtWidgets.QLabel(self.solver_frame)
        self.solver_label.setObjectName("solver_label")
        self.verticalLayout_7.addWidget(self.solver_label)
        self.frames_layout = QtWidgets.QHBoxLayout()
        self.frames_layout.setSpacing(1)
        self.frames_layout.setObjectName("frames_layout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.frames_layout.addItem(spacerItem3)
        self.frames_label = QtWidgets.QLabel(self.solver_frame)
        self.frames_label.setObjectName("frames_label")
        self.frames_layout.addWidget(self.frames_label)
        self.frames_lineEdit = QtWidgets.QLineEdit(self.solver_frame)
        self.frames_lineEdit.setObjectName("frames_lineEdit")
        self.frames_layout.addWidget(self.frames_lineEdit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.frames_layout.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.frames_layout)
        self.emptySpace_layout = QtWidgets.QHBoxLayout()
        self.emptySpace_layout.setObjectName("emptySpace_layout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.emptySpace_layout.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.emptySpace_layout)
        self.solver_layout.addWidget(self.solver_frame)
        self.verticalLayout_4.addLayout(self.solver_layout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.collection_label.setText(QtWidgets.QApplication.translate("Form", "Collection", None, -1))
        self.collectionAdd_toolButton.setText(QtWidgets.QApplication.translate("Form", "+", None, -1))
        self.collectionRemove_toolButton.setText(QtWidgets.QApplication.translate("Form", "-", None, -1))
        self.object_label.setText(QtWidgets.QApplication.translate("Form", "Objects", None, -1))
        self.objectAdd_toolButton.setText(QtWidgets.QApplication.translate("Form", "+", None, -1))
        self.objectRemove_toolButton.setText(QtWidgets.QApplication.translate("Form", "-", None, -1))
        self.attribute_label.setText(QtWidgets.QApplication.translate("Form", "Attributes", None, -1))
        self.attributeAdd_toolButton.setText(QtWidgets.QApplication.translate("Form", "+", None, -1))
        self.attributeRemove_toolButton.setText(QtWidgets.QApplication.translate("Form", "-", None, -1))
        self.solver_label.setText(QtWidgets.QApplication.translate("Form", "Solver", None, -1))
        self.frames_label.setText(QtWidgets.QApplication.translate("Form", "Frames", None, -1))
        self.frames_lineEdit.setText(QtWidgets.QApplication.translate("Form", "1001-1101", None, -1))

