// Copyright (C) 2026 David Cattermole.
//
// This file is part of mmSolver.
//
// mmSolver is free software: you can redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// mmSolver is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with mmSolver.  If not, see <https://www.gnu.org/licenses/>.
// ====================================================================

use std::io::Write;
use std::path::Path;
use std::process::Command;

fn main() {
    let out_dir = std::env::var("OUT_DIR").unwrap();

    // Generate stub implementations of mmsolverlibs::build_info
    // functions. These are normally generated by CMake, but for
    // standalone Rust builds we provide minimal stubs.
    let stubs_path = Path::new(&out_dir).join("build_constant_stubs.cpp");
    {
        let mut f = std::fs::File::create(&stubs_path).unwrap();
        write!(
            f,
            r#"#include <mmsolverlibs/buildConstant.h>

namespace mmsolverlibs {{
namespace build_info {{

const char* const project_name() {{ return "mmSolver"; }}
const char* const project_version_major() {{ return "0"; }}
const char* const project_version_minor() {{ return "0"; }}
const char* const project_version_patch() {{ return "0"; }}
const char* const project_version_tweak() {{ return "0"; }}
const char* const project_version() {{ return "0.0.0.0"; }}
const char* const project_homepage_url() {{ return ""; }}
const char* const project_description() {{ return ""; }}
const char* const project_author() {{ return ""; }}
const char* const project_copyright() {{ return ""; }}
const char* const system() {{ return "standalone"; }}
const char* const source_dir() {{ return ""; }}
const char* const build_type() {{ return "Release"; }}
const char* const build_date_time() {{ return ""; }}
const char* const git_branch() {{ return ""; }}
const char* const git_commit_hash_long() {{ return ""; }}
const char* const git_commit_hash_short() {{ return ""; }}
const char* const cmake_version() {{ return ""; }}
const char* const cmake_generator() {{ return ""; }}
const char* const cxx_compiler() {{ return ""; }}
const char* const cxx_linker() {{ return ""; }}

}}  // namespace build_info
}}  // namespace mmsolverlibs
"#
        )
        .unwrap();
    } // Close the file before compilation (required on Windows).

    // Extract LDPK (Lens Distortion Plugin Kit) headers from the
    // bundled tarball. LDPK is a header-only C++ library from
    // 3DEqualizer.
    //
    // The LDPK_INCLUDE_DIR env var can override this to use a
    // pre-installed copy.
    println!("cargo:rerun-if-env-changed=LDPK_INCLUDE_DIR");
    let ldpk_include = if let Ok(dir) = std::env::var("LDPK_INCLUDE_DIR") {
        dir
    } else {
        let ldpk_extract_dir = Path::new(&out_dir).join("ldpk");
        if !ldpk_extract_dir.join("ldpk-2.12.0/include/ldpk").exists() {
            // Find the project root relative to this crate
            // (lib/cppbind/mmlens/).
            let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
            let project_root = Path::new(&manifest_dir)
                .parent()
                .unwrap()
                .parent()
                .unwrap()
                .parent()
                .unwrap();
            let tarball =
                project_root.join("external/archives/ldpk-2.12.0.tar");
            if !tarball.exists() {
                panic!(
                    "LDPK tarball not found at {}. Set LDPK_INCLUDE_DIR or \
                     ensure external/archives/ldpk-2.12.0.tar exists.",
                    tarball.display()
                );
            }

            std::fs::create_dir_all(&ldpk_extract_dir).unwrap();
            let status = Command::new("tar")
                .arg("xf")
                .arg(&tarball)
                .arg("-C")
                .arg(&ldpk_extract_dir)
                .status()
                .expect("Failed to run tar to extract LDPK");
            if !status.success() {
                panic!("Failed to extract LDPK tarball");
            }
        }
        ldpk_extract_dir
            .join("ldpk-2.12.0/include")
            .to_str()
            .unwrap()
            .to_string()
    };

    let cpp_files = [
        "src/_cxxbridge.cpp",
        "src/distortion_layers.cpp",
        "src/distortion_process.cpp",
        "src/lens_model_3de_classic.cpp",
        "src/lens_model_3de_radial_decentered_deg_4_cylindric.cpp",
        "src/lens_model_3de_anamorphic_deg_4_rotate_squeeze_xy.cpp",
        "src/lens_model_3de_anamorphic_deg_4_rotate_squeeze_xy_rescaled.cpp",
        "src/lens_model_3de_anamorphic_deg_6_rotate_squeeze_xy.cpp",
        "src/lens_model_3de_anamorphic_deg_6_rotate_squeeze_xy_rescaled.cpp",
        "src/lens_model_passthrough.cpp",
        "src/lib.cpp",
    ];

    let mut build = cc::Build::new();
    build
        .cpp(true)
        .warnings(false)
        .include("include")
        .include("src")
        .include("../mmcore/include")
        .include("../../mmsolverlibs/include")
        .include(&ldpk_include)
        .file(&stubs_path)
        .files(&cpp_files);

    // MSVC does not recognise "c++11"; use "c++14" (the oldest it
    // accepts) there and keep "c++11" everywhere else.
    //
    // Also define _WINDOWS so that ldpk_error.h takes its Windows
    // branch (using <windows.h>) instead of the POSIX branch
    // (using <pthread.h>), which MSVC does not provide.
    if build.get_compiler().is_like_msvc() {
        build.std("c++14").define("_WINDOWS", None);
    } else {
        build.std("c++11");
    }
    build.compile("mmlens_cpp");

    // Re-run if any C++ source or header changes.
    for f_name in &cpp_files {
        println!("cargo:rerun-if-changed={}", f_name);
    }
    println!("cargo:rerun-if-changed=include");
}
