# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\catte\dev\mayaMatchMoveSolver\python\mmSolver\tools\loadmarker\ui\loadmarker_layout.ui'
#
# Created: Tue Dec 25 23:12:26 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(615, 413)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.filepath_horizontalLayout = QtWidgets.QHBoxLayout()
        self.filepath_horizontalLayout.setObjectName("filepath_horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.filepath_horizontalLayout.addItem(spacerItem1)
        self.filepath_label = QtWidgets.QLabel(Form)
        self.filepath_label.setObjectName("filepath_label")
        self.filepath_horizontalLayout.addWidget(self.filepath_label)
        self.filepath_lineEdit = QtWidgets.QLineEdit(Form)
        self.filepath_lineEdit.setObjectName("filepath_lineEdit")
        self.filepath_horizontalLayout.addWidget(self.filepath_lineEdit)
        self.filepath_pushButton = QtWidgets.QPushButton(Form)
        self.filepath_pushButton.setObjectName("filepath_pushButton")
        self.filepath_horizontalLayout.addWidget(self.filepath_pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.filepath_horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.filepath_horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem3)
        self.fileInfo_horizontalLayout = QtWidgets.QHBoxLayout()
        self.fileInfo_horizontalLayout.setObjectName("fileInfo_horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.fileInfo_horizontalLayout.addItem(spacerItem4)
        self.fileInfo_plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.fileInfo_plainTextEdit.setObjectName("fileInfo_plainTextEdit")
        self.fileInfo_horizontalLayout.addWidget(self.fileInfo_plainTextEdit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.fileInfo_horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.fileInfo_horizontalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.loadoptions_verticalLayout = QtWidgets.QVBoxLayout()
        self.loadoptions_verticalLayout.setSpacing(6)
        self.loadoptions_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.loadoptions_verticalLayout.setObjectName("loadoptions_verticalLayout")
        self.camera_horizontalLayout = QtWidgets.QHBoxLayout()
        self.camera_horizontalLayout.setObjectName("camera_horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.camera_horizontalLayout.addItem(spacerItem7)
        self.camera_label = QtWidgets.QLabel(Form)
        self.camera_label.setObjectName("camera_label")
        self.camera_horizontalLayout.addWidget(self.camera_label)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.camera_horizontalLayout.addItem(spacerItem8)
        self.camera_comboBox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_comboBox.sizePolicy().hasHeightForWidth())
        self.camera_comboBox.setSizePolicy(sizePolicy)
        self.camera_comboBox.setObjectName("camera_comboBox")
        self.camera_horizontalLayout.addWidget(self.camera_comboBox)
        self.cameraUpdate_pushButton = QtWidgets.QPushButton(Form)
        self.cameraUpdate_pushButton.setObjectName("cameraUpdate_pushButton")
        self.camera_horizontalLayout.addWidget(self.cameraUpdate_pushButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.camera_horizontalLayout.addItem(spacerItem9)
        self.loadoptions_verticalLayout.addLayout(self.camera_horizontalLayout)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.loadoptions_verticalLayout.addWidget(self.line)
        self.imageRes_horizontalLayout = QtWidgets.QHBoxLayout()
        self.imageRes_horizontalLayout.setObjectName("imageRes_horizontalLayout")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.imageRes_horizontalLayout.addItem(spacerItem10)
        self.imageResWidth_label = QtWidgets.QLabel(Form)
        self.imageResWidth_label.setObjectName("imageResWidth_label")
        self.imageRes_horizontalLayout.addWidget(self.imageResWidth_label)
        self.imageResWidth_spinBox = QtWidgets.QSpinBox(Form)
        self.imageResWidth_spinBox.setMaximum(99999)
        self.imageResWidth_spinBox.setObjectName("imageResWidth_spinBox")
        self.imageRes_horizontalLayout.addWidget(self.imageResWidth_spinBox)
        self.imageResHeight_spinBox = QtWidgets.QSpinBox(Form)
        self.imageResHeight_spinBox.setMaximum(99999)
        self.imageResHeight_spinBox.setObjectName("imageResHeight_spinBox")
        self.imageRes_horizontalLayout.addWidget(self.imageResHeight_spinBox)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.imageRes_horizontalLayout.addItem(spacerItem11)
        self.loadoptions_verticalLayout.addLayout(self.imageRes_horizontalLayout)
        self.verticalLayout_4.addLayout(self.loadoptions_verticalLayout)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.filepath_label.setText(QtWidgets.QApplication.translate("Form", "File Path", None, -1))
        self.filepath_pushButton.setText(QtWidgets.QApplication.translate("Form", "Browse", None, -1))
        self.camera_label.setText(QtWidgets.QApplication.translate("Form", "Camera", None, -1))
        self.cameraUpdate_pushButton.setText(QtWidgets.QApplication.translate("Form", "Refresh List", None, -1))
        self.imageResWidth_label.setText(QtWidgets.QApplication.translate("Form", "Image Resolution", None, -1))

